from __future__ import annotations

import argparse
import os
import shutil
import tempfile
import zipapp
from pathlib import Path, PurePosixPath
from typing import Sequence
from zipfile import BadZipFile, ZIP_STORED, ZipFile, ZipInfo


SOURCE_ALLOWLIST = (
    "citation_canary/__init__.py",
    "citation_canary/__main__.py",
    "citation_canary/catalog.py",
    "citation_canary/demo.py",
    "citation_canary/hwpx.py",
    "citation_canary/references.py",
    "citation_canary/report.py",
    "citation_canary/review_io.py",
    "citation_canary/review.py",
    "citation_canary/comparison.py",
    "citation_canary/review_html.py",
    "citation_canary/scanner.py",
)
METADATA_ALLOWLIST = ("LICENSE",)
ARCHIVE_ALLOWLIST = frozenset(
    (*SOURCE_ALLOWLIST, *METADATA_ALLOWLIST, "citation_canary/", "__main__.py")
)


class ZipappBuildError(RuntimeError):
    """The allowlisted source could not produce the exact safe archive."""


def _native_path(root: Path, relative: str) -> Path:
    return root.joinpath(*PurePosixPath(relative).parts)


def _copy_allowlisted_source(source_root: Path, staging_root: Path) -> None:
    expected = set(SOURCE_ALLOWLIST)
    present = {
        path.relative_to(source_root).as_posix()
        for path in source_root.rglob("*")
        if path.is_file()
        and "__pycache__" not in path.parts
        and path.suffix.casefold() not in {".pyc", ".pyo"}
    }
    if present != expected:
        raise ZipappBuildError("Source tree does not match the file allowlist.")

    for relative in SOURCE_ALLOWLIST:
        source = _native_path(source_root, relative)
        if not source.is_file() or source.is_symlink():
            raise ZipappBuildError("Allowlisted source file is unavailable.")
        destination = _native_path(staging_root, relative)
        destination.parent.mkdir(parents=True, exist_ok=True)
        # Git may materialize text with CRLF on Windows. Normalize the
        # allowlisted Python sources so the archive matches the repository
        # blobs and remains byte-reproducible across checkout settings.
        destination.write_bytes(source.read_bytes().replace(b"\r\n", b"\n"))

    staged = {
        path.relative_to(staging_root).as_posix()
        for path in staging_root.rglob("*")
        if path.is_file()
    }
    if staged != expected:
        raise ZipappBuildError("Staging tree does not match the file allowlist.")


def _copy_allowlisted_metadata(metadata_root: Path, staging_root: Path) -> None:
    for relative in METADATA_ALLOWLIST:
        source = _native_path(metadata_root, relative)
        destination = _native_path(staging_root, relative)
        if not source.is_file() or source.is_symlink():
            raise ZipappBuildError("Allowlisted metadata file is unavailable.")
        if destination.exists() or destination.is_symlink():
            raise ZipappBuildError("Allowlisted metadata collides with staged source.")
        destination.write_bytes(source.read_bytes().replace(b"\r\n", b"\n"))

    staged = {
        path.relative_to(staging_root).as_posix()
        for path in staging_root.rglob("*")
        if path.is_file()
    }
    if staged != set((*SOURCE_ALLOWLIST, *METADATA_ALLOWLIST)):
        raise ZipappBuildError("Staging tree does not match the file allowlist.")


def _verify_archive(
    archive_path: Path,
    *,
    sensitive_roots: tuple[Path, ...],
) -> None:
    try:
        with ZipFile(archive_path, mode="r") as archive:
            names = tuple(archive.namelist())
            if len(names) != len(set(names)) or set(names) != ARCHIVE_ALLOWLIST:
                raise ZipappBuildError(
                    "Archive members do not match the exact allowlist."
                )
            sensitive_spellings = {
                spelling
                for root in sensitive_roots
                for spelling in (
                    str(root.resolve()),
                    str(root.resolve()).replace("\\", "/"),
                    str(root.resolve()).replace("/", "\\"),
                )
            }
            for member in archive.infolist():
                lowered = member.filename.casefold()
                if "__pycache__" in lowered or lowered.endswith((".pyc", ".pyo")):
                    raise ZipappBuildError("Archive contains generated bytecode.")
                if member.is_dir():
                    continue
                payload = archive.read(member)
                for spelling in sensitive_spellings:
                    if (
                        spelling.encode("utf-8") in payload
                        or spelling.encode("utf-16-le") in payload
                    ):
                        raise ZipappBuildError(
                            "Archive contains local absolute path metadata."
                        )
    except BadZipFile as error:
        raise ZipappBuildError("Built artifact is not a readable ZIP archive.") from error


def _make_deterministic_archive(source: Path, target: Path) -> None:
    with ZipFile(source, mode="r") as archive:
        members = tuple(
            (info.filename, archive.read(info), info.is_dir())
            for info in sorted(archive.infolist(), key=lambda value: value.filename)
        )

    with target.open("wb") as stream:
        stream.write(b"#!/usr/bin/env python3\n")
        with ZipFile(stream, mode="w") as archive:
            for name, payload, is_directory in members:
                info = ZipInfo(filename=name, date_time=(1980, 1, 1, 0, 0, 0))
                info.create_system = 0
                info.compress_type = ZIP_STORED
                if is_directory:
                    info.external_attr = 0x10
                archive.writestr(info, payload)


def _install_archive(temporary_archive: Path, target: Path) -> None:
    try:
        os.replace(temporary_archive, target)
        return
    except OSError as error:
        # GitHub Windows runners keep RUNNER_TEMP on D: while Python's temp
        # directory can be on C:. Stage a complete copy beside the target
        # before the final replace when those volumes differ.
        if getattr(error, "winerror", None) != 17:
            raise

    sibling: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            dir=target.parent,
            prefix=f".{target.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            sibling = Path(handle.name)
        shutil.copyfile(temporary_archive, sibling)
        os.replace(sibling, target)
        sibling = None
    finally:
        if sibling is not None:
            try:
                sibling.unlink(missing_ok=True)
            except OSError:
                pass


def build_zipapp(source_root: Path, target: Path) -> None:
    source_root = Path(source_root).resolve()
    target = Path(target).resolve()
    if target == source_root or source_root in target.parents:
        raise ZipappBuildError("Target must be outside the source tree.")
    if target in {
        _native_path(source_root.parent, relative).resolve()
        for relative in METADATA_ALLOWLIST
    }:
        raise ZipappBuildError("Target must not replace allowlisted metadata.")
    if not source_root.is_dir():
        raise ZipappBuildError("Source root is unavailable.")
    if not target.parent.is_dir():
        raise ZipappBuildError("Target parent is unavailable.")

    with tempfile.TemporaryDirectory(
        prefix="citation-canary-allowlist-",
    ) as temporary_directory:
        build_root = Path(temporary_directory)
        staging_root = build_root / "staging"
        staging_root.mkdir()
        _copy_allowlisted_source(source_root, staging_root)
        _copy_allowlisted_metadata(source_root.parent, staging_root)
        source_archive = build_root / f".{target.name}.source"
        temporary_archive = build_root / target.name
        zipapp.create_archive(
            source=staging_root,
            target=source_archive,
            main="citation_canary.__main__:_run",
            interpreter="/usr/bin/env python3",
            compressed=True,
        )
        _make_deterministic_archive(source_archive, temporary_archive)
        _verify_archive(
            temporary_archive,
            sensitive_roots=(source_root.parent, source_root, staging_root),
        )
        _install_archive(temporary_archive, target)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="build-citation-canary-zipapp")
    parser.add_argument("--source", required=True)
    parser.add_argument("--output", required=True)
    arguments = parser.parse_args(argv)
    try:
        build_zipapp(Path(arguments.source), Path(arguments.output))
    except (OSError, ZipappBuildError):
        print("ZIPAPP_BUILD_FAILED")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
